{% set name = "testslide" %}
{% set version = "2.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/TestSlide-{{ version }}.tar.gz
  sha256: d25890d5c383f673fac44a5f9e2561b7118d04f29f2c2b3d4f549e6db94cb34d

build:
  noarch: python
  entry_points:
    - testslide=testslide.cli:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.7
    - setuptools >=38.6.0
  run:
    - psutil >=5.6.7
    - pygments >=2.2.0
    - python >=3.7
    - typeguard >=2.10.0

test:
  imports:
    - testslide
  commands:
    - pip check
    - testslide --help
  requires:
    - pip

about:
  home: https://github.com/facebook/TestSlide
  doc_url: https://testslide.readthedocs.io/en/main/
  summary: A test framework for Python that makes mocking and iterating over code with tests a breeze
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
